"""remove salt, update encrypted fields to LargeBinary

Revision ID: 6c3b3a960b0d
Revises: 93f749a4212d
Create Date: 2026-04-21 18:30:40.445236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3b3a960b0d'
down_revision = '93f749a4212d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('salt')

    with op.batch_alter_table('vault_entries', schema=None) as batch_op:
        batch_op.alter_column(
            'password',
            existing_type=sa.TEXT(),
            type_=sa.LargeBinary(),
            existing_nullable=False,
            postgresql_using='password::bytea'
        )
        batch_op.alter_column(
            'iv',
            existing_type=sa.VARCHAR(length=255),
            type_=sa.LargeBinary(),
            existing_nullable=False,
            postgresql_using='iv::bytea'
        )
        batch_op.alter_column(
            'auth_tag',
            existing_type=sa.VARCHAR(length=255),
            type_=sa.LargeBinary(),
            existing_nullable=False,
            postgresql_using='auth_tag::bytea'
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('vault_entries', schema=None) as batch_op:
        batch_op.alter_column(
            'auth_tag',
            existing_type=sa.LargeBinary(),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False,
            postgresql_using='encode(auth_tag, \'escape\')'
        )
        batch_op.alter_column(
            'iv',
            existing_type=sa.LargeBinary(),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False,
            postgresql_using='encode(iv, \'escape\')'
        )
        batch_op.alter_column(
            'password',
            existing_type=sa.LargeBinary(),
            type_=sa.TEXT(),
            existing_nullable=False,
            postgresql_using='encode(password, \'escape\')'
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('salt', sa.VARCHAR(length=255), nullable=False)
        )

    # ### end Alembic commands ###
