"""Added cascade delete to tags

Revision ID: 93f749a4212d
Revises: 04b5a263eb12
Create Date: 2026-03-22 20:48:27.340288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f749a4212d'
down_revision = '04b5a263eb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
